# Generated by Django 4.2.26 on 2025-12-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_password_hash_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login_at",
        ),
    ]
