# Generated by Django 4.2.26 on 2025-12-09 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Enter a valid email address."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username must be 3-30 characters long and can only contain letters, numbers, and underscores.",
                        regex="^[a-zA-Z0-9_]{3,30}$",
                    )
                ],
            ),
        ),
    ]
